# Generated by Django 4.2.23 on 2025-06-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoststat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
